### ISSUE TITLE
err TypeError: Cannot read properties of undefined (reading 'contentWindow')

### ISSUE THREAD

**Issue by shinokada** [shinokada/svelte-utterances#6]
The following code returns error:

```
...
const iFrame = document.getElementsByTagName("iframe")[0];
        iFrame.contentWindow.postMessage(
...
```

> err TypeError: Cannot read properties of undefined (reading 'contentWindow')
>     at Object.u.$$.update (doc.svelte-98be7cc1.js:1:1097)
>     at ve (vendor-60873d7e.js:1:7294)
>     at new be (doc.svelte-98be7cc1.js:1:1258)
>     at de (doc.svelte-98be7cc1.js:1:3349)
>     at ve (vendor-60873d7e.js:1:7340)
>     at new $e (doc.svelte-98be7cc1.js:1:5518)
>     at zt (index.md-070d2b67.js:18:3876)
>     at ve (vendor-60873d7e.js:1:7340)
>     at new Kt (index.md-070d2b67.js:18:4295)
>     at Array.Ve (start-7fe98c40.js:1:2515)

**Comment by shinokada** [comment]
This can be solved using if statement:

```
if (iFrame) {
          iFrame.contentWindow.postMessage(
            { type: "set-theme", theme },
            "https://utteranc.es"
          );
        }
```
